### ISSUE TITLE
Umlauts?

### ISSUE THREAD

**Issue by mjut** [nfriedly/spam-free-php-contact-form#2]
Nice work! I like this simple approach for preventing spam-mails!
Unfortunately, Umlauts (ö ä ü ß ...) are not being sent properly.

How can I fix this? e.g. setting the mail to utf-8?

**Comment by nfriedly** [comment]
Try adding ` "Content-type: text/plain; charset=utf-8" ` to the headers. (Use `"\r\n"` to separate multiple headers)

**Comment by mjut** [comment]
Thanks – I did some testing, but I could not manage to get it working:
I am not sure where to put this extra header...

**Comment by nfriedly** [comment]
Are you on the simple version or the advanced version?

**Comment by mjut** [comment]
It's the advanced one.

**Comment by mjut** [comment]
I got it! I added this:
`	if( $_POST['email'] && !preg_match( "/[\r\n]/", $_POST['email']) ) {
	  $headers = "From: $_POST[email]" . "\r\n";
	  $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
	} else {
	  $headers = "From: $youremail" . "\r\n";
	  $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
	}
`
That was it.
Thanks for pointing me into the correct direction!

**Comment by nfriedly** [comment]
Awesome! Sorry I didn't get back to you, I was out all weekend. But, glad to hear that you figured it out :)
