### ISSUE TITLE
Line breaks from textarea

### ISSUE THREAD

**Issue by mjut** [nfriedly/spam-free-php-contact-form#3]
Here is another thing:

The form sends all fields like it should, except that text area seems to cut all line breaks. 
I found some code, that seems to make sure line breaks are being rendered:

`nl2br($_POST["message"]);`

But how do I combine this with the (advanced) form?

Thanks for your help!

Cheers
Stephan

**Comment by nfriedly** [comment]
Hi Stephan,

The line breaks should be in the message, is your email client hiding them, perhaps?

I don't think the `nl2br` function will do what you want, at least not without some extra work - it is intended for HTML output, and both the simple and advanced forms are sending out plain text. If you want to try it out, though, it may be easier to just apply it to the entire `$body`, so add this around line 15:

```php
$body = nl2br($body);
```

And, then, to let email clients know that you're now sending HTML, add something like this around line 24:

```php
$headers .= "\r\nContent-Type: text/html"
```

I haven't tested these myself, but something along those lines should do the trick.

**Comment by mjut** [comment]
This is perfekt. Thanks for the support!
